#!/opt/mydan/perl/bin/perl -I/opt/AntDen/lib
use strict;
use warnings;
use AntDen;

use MYDan::Util::OptConf;
use AntDen::Slave;

$| ++;

$MYDan::Util::OptConf::THIS = 'antden';

=head1 SYNOPSIS

 $0 --taskid J.20191110.120502.435819.450.001

=cut

my $option = MYDan::Util::OptConf->load();
my %o = $option->get( qw( taskid=s ) )->dump();
$option->assert( 'taskid' );

AntDen::Slave->new( %{$o{slave}} )->stop( +{ taskid => $o{taskid} } );
