#!/opt/mydan/perl/bin/perl -I/opt/AntDen/lib
use strict;
use warnings;
use AntDen;

use MYDan::Util::OptConf;
use AntDen::Slave;

use Time::HiRes 'gettimeofday';

$| ++;

$MYDan::Util::OptConf::THIS = 'antden';

=head1 SYNOPSIS

 $0 

=cut

my %o = MYDan::Util::OptConf->load()->get()->dump();

my ($sec ,$usec ) = gettimeofday;
my $taskid = sprintf "%s.%06d.%03d.%03d", POSIX::strftime( "J.%Y%m%d.%H%M%S", localtime( $sec ) ), $usec, rand( 1000 ), 1;

print "taskid: $taskid\n";
AntDen::Slave->new( %{$o{slave}} )->start(
    +{
        taskid => $taskid,
        resources => +{
			'CPU:0' => 1,
        },
        task => +{
            executer => 'exec',
            param => +{
				exec => 'sleep 100'
			}
        }	
    }
);
