#!# perl: code/
use warnings;
use strict;

=head3 param

  resources:
    CPU:0: 2
    GPU:1: 1
    GPU:3: 1
  param:
    exec: sleep 100

=head3 return

  return executeid, for stop and status, maybe pid or container id

=cut

return sub
{
    my %param = @_;
	
	my $pid = fork;
	return $pid if $pid;
	
	exec $param{param}{exec};

	exit 0;
};
