#!# perl: code/
use warnings;
use strict;

use MYDan::Util::OptConf;
use AntDen::Scheduler;

return sub
{
    my %o = MYDan::Util::OptConf->load()->dump( 'antden' );
    return AntDen::Scheduler->new( %{$o{scheduler}} )->applyResources( @_ );
};
