#!/opt/mydan/perl/bin/perl -I/opt/AntDen/lib
use strict;
use warnings;
use AntDen;
use FindBin qw( $RealBin );
use YAML::XS;
use MYDan;

=head1 SYNOPSIS

 $0

=cut

system "killall AntDen_scheduler_supervisor";
system "killall AntDen_scheduler_service";

while(1)
{
    sleep 1;
    last unless my @x = `ps -ef|grep [A]ntDen_scheduler_`;
}

die "start $_ fail: $!" if system "$MYDan::PATH/dan/tools/supervisor --name AntDen_scheduler_supervisor --cmd '$AntDen::PATH/scheduler/service/scheduler.service' --log '$AntDen::PATH/logs/scheduler'";

sleep 1;

print "Process:\n";
system "ps -ef|grep [A]ntDen_scheduler_";
