#!/opt/mydan/perl/bin/perl -I/opt/AntDen/lib
use strict;
use warnings;
use AntDen;
use FindBin qw( $RealBin );
use YAML::XS;
use MYDan;

=head1 SYNOPSIS

 $0

=cut

system "killall AntDen_controller_supervisor";
system "killall AntDen_controller_service";

while(1)
{
    sleep 1;
    last unless my @x = `ps -ef|grep [A]ntDen_controller_`;
}

die "start $_ fail: $!" if system "$MYDan::PATH/dan/tools/supervisor --name AntDen_controller_supervisor --cmd '$AntDen::PATH/controller/service/controller.service' --log '$AntDen::PATH/logs/controller'";

sleep 1;

print "Process:\n";
system "ps -ef|grep [A]ntDen_controller_";
